spring:
  profiles:
    default:
      local

  application:
    name: woomulwoomul-backend

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
        use_sql_comments: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 50MB

logging:
  file:
    name: woomulwoomul-rolling.log


springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  show-actuator: true
  paths-to-match: /api/**
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

sentry:
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: info

api:
  master:
    id: alloon
  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}
    time:
      access: ${JWT_ACCESS}
      refresh: ${JWT_REFRESH}
  mail:
    address: ${MAIL_ADDRESS}