spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
        use_sql_comments: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 50MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  file:
    name: woomulwoomul-rolling.log

sentry:
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: info

#cloud:
#  aws:
#    credentials:
#      access-key: ${AWS_ACCESS_KEY}
#      secret-key: ${AWS_SECRET_KEY}
#    region:
#      static: ${AWS_REGION}
#    s3:
#      bucket: ${AWS_BUCKET}

api:
  master:
    id: woomulwoomul
  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}
    time:
      access: ${JWT_ACCESS}
      refresh: ${JWT_REFRESH}
  mail:
    address: ${MAIL_ADDRESS}