spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 50MB

server:
  port: 8083

logging:
  file:
    name: woomulwoomul-batch-rolling.log

sentry:
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: info

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET}

api:
  master:
    id: woomulwoomul
  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}
    time:
      access: ${JWT_ACCESS}
      refresh: ${JWT_REFRESH}
  mail:
    address: ${MAIL_ADDRESS}