spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/woomulwoomul
    username: sa
    password:

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

logging:
  config: classpath:logback/dev-logback.xml

sentry:
  dsn:

api:
  name: "Woomulwoomul Test"

web:
  domain: "https://www-woomulwoomul-dev.nogamsung.com"