spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  sql:
    init:
      mode: ${SQL_INIT_MODE}

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://${OAUTH2_HOST}/login/oauth2/code/kakao

logging:
  config: classpath:logback/prd-logback.xml

sentry:
  dsn: ${SENTRY_DSN}
  environment: dev

api:
  name: "Woomulwoomul Dev"