name: Main - CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
#          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
#          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
#          AWS_REGION: ${{ secrets.AWS_REGION }}
#          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          JWT_DOMAIN: ${{ secrets.JWT_DOMAIN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ACCESS: ${{ secrets.JWT_ACCESS }}
          JWT_REFRESH: ${{ secrets.JWT_REFRESH }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAX_FILE_SIZE: ${{ secrets.MAX_FILE_SIZE }}
          MAX_REQUEST_SIZE: ${{ secrets.MAX_REQUEST_SIZE }}

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.9
        with:
          coverage_results_path: build/reports/jacoco/test/jacocoTestReport.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          publish_only_summary: true
          minimum_coverage: 1
          fail_below_threshold: true

      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-html
          path: build/reports/jacoco/test/html
          retention-days: 90

      - name: Build and Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: gs97ahn/server
          tags: woomulwoomul-prod, woomulwoomul-v1.0.0
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}